# Generated by Django 4.2 on 2026-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_classroom_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classrooms',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.classroom'),
        ),
    ]
