# Generated by Django 4.2 on 2026-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='PARENT', max_length=10),
        ),
    ]
